<?php

use Icinga\Module\Monitoring\Object\Host;

if (! $this->compact): ?>
<div class="controls separated">
  <?= $this->tabs; ?>
  <div class="dontprint">
    <?= $this->render('list/components/selectioninfo.phtml'); ?>
    <?= $this->render('list/components/hostssummary.phtml'); ?>
  </div>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
<H1>IT Operations Hosts</H1>
<?php

if (count($hosts) === 0) {
    echo $this->translate('No hosts found matching the filter') . '</div>';
    return;
}
?>

<table
    data-base-target="_next"
    class="action multiselect"
    data-icinga-multiselect-url="<?= $this->href('monitoring/hosts/show') ?>"
    data-icinga-multiselect-data="host"
>
  <tbody>
  <?php foreach($hosts as $host):

    $hostStateName = Host::getStateText($host->host_state);
    $hostLink = $this->href('itoperations/host/show', array('host' => $host->host_name));


    ?>
    <tr class="state <?= $hostStateName ?><?= $host->host_handled ? ' handled' : '' ?>">
      <!-- State -->
      <td class="state">
        <strong><?= Host::getStateText($host->host_state, true); ?></strong>
        <?php if ((int) $host->host_state !== 99): ?>
          <br />
          <?= $this->timeSince($host->host_last_state_change, $this->compact) ?>
          <?php if ((int) $host->host_state > 0 && (int) $host->host_state_type === 0): ?>
            <br />
            <strong>Soft <?= $host->host_attempt ?></strong>
          <?php endif ?>
        <?php endif ?>
      </td>

      <!-- Host / Status / Output -->
      <td>
        <?= $this->iconImage()->host($host) ?>
        <span class="objectflags"><?= implode(' ', $this->hostFlags($host)) ?></span>
        <?= $this->qlink(
          $host->host_display_name,
          $hostLink,
          null,
          array(
            'title' => sprintf($this->translate('Show detailed information for host %s'), $host->host_display_name)
          )
        ); ?>
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>
</div>
