<?php
use Icinga\Module\Monitoring\Object\Host;

if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
</div>
<?php endif ?>
<div class="content">
<H1>IT Operations Host Groups</H1>
<?php

if (count($hostgroups) === 0) {
    echo $this->translate('No hostgroups found matching the filter') . '</div>';
    return;
}
?>
  <table class="groupview action" data-base-target="_next">
	<thead>
      <!--     <th><?= $this->translate('Last Problem'); ?></th>
      <th><?= $this->translate('Host Group'); ?></th>
      <th><?= $this->translate('Total Hosts'); ?></th>
      <th><?= $this->translate('Host States'); ?></th>
      <th><?= $this->translate('Total Services'); ?></th>
      <th><?= $this->translate('Service States'); ?></th> -->
    </thead>
    <tbody>
    <?php foreach ($hostgroups as $h):?>
      <tr>
        <td class="groupname">
          <?= $this->qlink(
            $h->hostgroup_alias,
            'itoperations/list/hosts',
            array('hostgroup_name' => $h->hostgroup_name),
            array('title' => sprintf($this->translate('List all hosts in the group "%s"'), $h->hostgroup_alias))
          ); ?>
        </td>
      <!--  <td class="total"> -->
        <?php //print $h->hosts_total;?>
        <!--</td>-->
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
</div>
